In [30]:
import pandas as pd

ordersdf = pd.read_csv("./Dataset/orders.csv")
customersdf = pd.read_csv("./Dataset/customers.csv")
productsdf = pd.read_csv("./Dataset/products.csv")

In [31]:
ordersdf.head()

   OrderID  CustomerID ProductID  Quantity
0      101           1      P101         2
1      102           2      P102         1
2      103           3      P101         3
3      104           4      P103         2
4      105           2      P104         5

In [32]:
customersdf.head()

   CustomerID CustomerName       City
0           1         John    Chennai
1           2         Emma  Bangalore
2           3          Raj  Hyderabad
3           4          NaN       Pune

In [33]:
productsdf.head()

  ProductID   Product  Price
0      P101    Laptop  50000
1      P102     Mouse    800
2      P103  Keyboard   1500
3      P104   Monitor  12000

In [34]:
dfs = {
    "Order": ordersdf,
    "Customer": customersdf,
    "Product": productsdf
}

for key, value in dfs.items():
    print("DataFrame: ", key)
    print("Columns: ", ", ".join(value.columns.tolist()))
    print()

DataFrame:  Order
Columns:  OrderID, CustomerID, ProductID, Quantity

DataFrame:  Customer
Columns:  CustomerID, CustomerName, City

DataFrame:  Product
Columns:  ProductID, Product, Price

In [35]:
# Missing customer names

dfs["Customer"]["CustomerName"] = dfs["Customer"]["CustomerName"].fillna("Unknown")

In [36]:
dfs["Customer"]

   CustomerID CustomerName       City
0           1         John    Chennai
1           2         Emma  Bangalore
2           3          Raj  Hyderabad
3           4      Unknown       Pune

In [38]:
orders_customer_df = dfs["Customer"].merge(dfs["Order"], on="CustomerID")

In [39]:
orders_customer_df

   CustomerID CustomerName       City  OrderID ProductID  Quantity
0           1         John    Chennai      101      P101         2
1           2         Emma  Bangalore      102      P102         1
2           2         Emma  Bangalore      105      P104         5
3           3          Raj  Hyderabad      103      P101         3
4           4      Unknown       Pune      104      P103         2

In [40]:
orders_customers_products_df = orders_customer_df.merge(dfs["Product"], on = "ProductID")

In [41]:
orders_customers_products_df

,CustomerID,CustomerName,City,OrderID,ProductID,Quantity,Product,Price
0,1,John,Chennai,101,P101,2,Laptop,50000
1,2,Emma,Bangalore,102,P102,1,Mouse,800
2,2,Emma,Bangalore,105,P104,5,Monitor,12000
3,3,Raj,Hyderabad,103,P101,3,Laptop,50000
4,4,Unknown,Pune,104,P103,2,Keyboard,1500

In [42]:
orders_customers_products_df["TotalSales"] = orders_customers_products_df["Quantity"] * orders_customers_products_df["Price"]

In [43]:
orders_customers_products_df

,CustomerID,CustomerName,City,OrderID,ProductID,Quantity,Product,Price,TotalSales
0,1,John,Chennai,101,P101,2,Laptop,50000,100000
1,2,Emma,Bangalore,102,P102,1,Mouse,800,800
2,2,Emma,Bangalore,105,P104,5,Monitor,12000,60000
3,3,Raj,Hyderabad,103,P101,3,Laptop,50000,150000
4,4,Unknown,Pune,104,P103,2,Keyboard,1500,3000

In [45]:
final_sales_df = orders_customers_products_df[["OrderID", "CustomerName", "Product", "TotalSales"]]

In [46]:
final_sales_df

   OrderID CustomerName   Product  TotalSales
0      101         John    Laptop      100000
1      102         Emma     Mouse         800
2      105         Emma   Monitor       60000
3      103          Raj    Laptop      150000
4      104      Unknown  Keyboard        3000

In [47]:
final_sales_df.columns = ["OrderID", "Customer", "Product", "TotalSales"]

In [48]:
final_sales_df

   OrderID Customer   Product  TotalSales
0      101     John    Laptop      100000
1      102     Emma     Mouse         800
2      105     Emma   Monitor       60000
3      103      Raj    Laptop      150000
4      104  Unknown  Keyboard        3000

In [ ]:
final_sales_df.to_csv("")