In [2]:
import numpy as np
import pandas as pd

# Task 1 - missing values

data = [10, 20, None, 40, None, 60]

data = np.array(data, dtype=object)

print("Missing Values: ", sum(x for x in pd.isna(data) if x == True))

Missing Values:  2

In [3]:
# Task 2 - remove duplicates

values = [10, 20, 20, 30, 40, 40, 50]

values = np.array(values)

print(np.unique(values))

[10 20 30 40 50]

In [4]:
# Task 3 - find mean

values = [10, 20, 30, 40, 50]

values = np.array(values)

print(np.mean(values))

30.0

In [6]:
# Task 4 - numpy stats

arr = np.array([10, 20, 30, 40, 50])

print("Mean : ", np.mean(arr))
print("Median : ", np.median(arr))
print("Standard Deviation : ", round(np.std(arr), 2))
print("Minimum : ", np.min(arr))
print("Maximum : ", np.max(arr))

Mean :  30.0
Median :  30.0
Standard Deviation :  14.14
Minimum :  10
Maximum :  50

In [9]:
# Task 5 - Normalize an array

arr = np.array([10, 20, 30, 40, 50])

minVal = np.min(arr)
maxVal = np.max(arr)

normalized = (arr - minVal) / (maxVal - minVal)

print(normalized)

[0.   0.25 0.5  0.75 1.  ]

In [10]:
# Task 6 - Standardization

arr = np.array([10, 20, 30, 40, 50])

meanVal = np.mean(arr)
stdVal = np.std(arr)

normalized = (arr - meanVal) / stdVal

print(normalized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]

In [11]:
# Task 7 - Boolean filtering

arr = np.array([10, 25, 30, 15, 40, 50])

vals = arr > 25

vals

array([False, False,  True, False,  True,  True])

In [12]:
# Task 8 - create dataframe

import pandas as pd

data = {
    "name": ["A", "B", "C", "D"],
    "age": [22, 25, 21, 30],
    "salary": [30000, 45000, 28000, 60000]
}

df = pd.DataFrame(data)
df

  name  age  salary
0    A   22   30000
1    B   25   45000
2    C   21   28000
3    D   30   60000

In [16]:
# Task 9 - select rows

df[df["salary"] > 40000]

  name  age  salary
1    B   25   45000
3    D   30   60000

In [17]:
# Task 10 - select multiple condition

df[(df["age"] > 22) & (df["salary"] > 30000)]

  name  age  salary
1    B   25   45000
3    D   30   60000

In [23]:
# Task 11 - missing values

df = pd.DataFrame({
    "age": [22, 25, None, 30, None],
    "salary": [30000, None, 40000, 60000, 50000]
})

print(df.isnull().sum())

df["age"] = df["age"].fillna(df["age"].mean())
df["salary"] = df["salary"].fillna(df["salary"].median())

print(df.isnull().sum())

age       2
salary    1
dtype: int64
age       0
salary    0
dtype: int64

In [24]:
# Task 12 - drop missing rows

df = df.dropna()

In [28]:
# Task 13 - remove duplicates

df = pd.DataFrame({
    "name": ["A", "B", "B", "C"],
    "age": [20, 25, 25, 30]
})

df = df.drop_duplicates()
df

  name  age
0    A   20
1    B   25
3    C   30

In [31]:
# Task 14 - GroupBy

df = pd.DataFrame({
    "city": ["Chennai", "Chennai", "Mumbai", "Mumbai", "Delhi"],
    "sales": [100, 200, 300, 100, 500]
})

df.groupby("city")["sales"].sum()

city
Chennai    300
Delhi      500
Mumbai     400
Name: sales, dtype: int64

In [32]:
# Task 15 - sorting

df = pd.DataFrame({
    "name": ["Madhan", "Arun", "Kumar", "Ravi", "Sanjay"],
    "age": [21, 24, 22, 26, 23],
    "salary": [35000, 50000, 42000, 30000, 60000]
})

df.sort_values(by="salary", ascending=False)

     name  age  salary
4  Sanjay   23   60000
1    Arun   24   50000
2   Kumar   22   42000
0  Madhan   21   35000
3    Ravi   26   30000

In [33]:
# Task 16 - create new features

df = pd.DataFrame({
    "height": [160, 170, 165, 180, 175],
    "weight": [55, 70, 60, 80, 75]
})

df["BMI"] = df["weight"] / df["height"] ** 2

df

   height  weight       BMI
0     160      55  0.002148
1     170      70  0.002422
2     165      60  0.002204
3     180      80  0.002469
4     175      75  0.002449

In [34]:
# Task 17 - apply a function

data = {
    "name": ["A", "B", "C", "D"],
    "age": [22, 25, 21, 30],
    "salary": [30000, 45000, 28000, 60000]
}

df = pd.DataFrame(data)

def categorise(salary):
    if salary >= 50000:
        return "HIGH"
    elif salary >= 30000 and salary < 50000:
        return "MEDIUM"
    else:
        return "LOW"

df["category"] = df["salary"].apply(categorise)

df

  name  age  salary category
0    A   22   30000   MEDIUM
1    B   25   45000   MEDIUM
2    C   21   28000      LOW
3    D   30   60000     HIGH

In [ ]:
# Task 18 - Basic EDA

print("Shape : ", df.shape)
print("Head : ", df.head())
print("Info : ", df.info())
print("Describe : ", df.describe())
print("Null Values : ", df.isnull().sum())
print("duplicates : ", df.duplicated().sum())

Shape :  (4, 4)
Head :    name  age  salary category
0    A   22   30000   MEDIUM
1    B   25   45000   MEDIUM
2    C   21   28000      LOW
3    D   30   60000     HIGH
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      4 non-null      str
 1   age       4 non-null      int64
 2   salary    4 non-null      int64
 3   category  4 non-null      str
dtypes: int64(2), str(2)
memory usage: 283.0 bytes
Info :  None
Describe :               age        salary
count   4.000000      4.000000
mean   24.500000  40750.000000
std     4.041452  14908.051516
min    21.000000  28000.000000
25%    21.750000  29500.000000
50%    23.500000  37500.000000
75%    26.250000  48750.000000
max    30.000000  60000.000000
Null Values :  name        0
age         0
salary      0
category    0
dtype: int64
duplicates :  0

In [38]:
# Source - https://stackoverflow.com/a/28155580
# Posted by Anand, modified by community. See post 'Timeline' for change history
# Retrieved 2026-09-14, License - CC BY-SA 4.0

# Task 19 - numerical columns

newdf = df.select_dtypes(include='number')

newdf

   age  salary
0   22   30000
1   25   45000
2   21   28000
3   30   60000

In [42]:
# Task 20 - categorical columns

coldf = df.select_dtypes(include='string')

coldf

  name category
0    A   MEDIUM
1    B   MEDIUM
2    C      LOW
3    D     HIGH

In [49]:
# Task 21 - Correlation

df = pd.DataFrame({
    "age": [22, 25, 28, 32, 35, 40, 45, 30, 27, 38],
    "salary": [25000, 30000, 35000, 50000, 55000, 70000, 85000, 45000, 32000, 65000],
    "experience": [1, 2, 3, 7, 8, 12, 15, 6, 4, 10],
    "purchased": [0, 0, 1, 1, 1, 1, 1, 0, 0, 1]
})

df.corr()

                 age    salary  experience  purchased
age         1.000000  0.994373    0.991709   0.737156
salary      0.994373  1.000000    0.993969   0.710321
experience  0.991709  0.993969    1.000000   0.672812
purchased   0.737156  0.710321    0.672812   1.000000

In [50]:
# Task 22 - Outlier Detection

column = df["salary"].describe()

Q1 = column["25%"]
Q3 = column["75%"]

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

def detect_outlier(salary):
    if salary < lower or salary > upper:
        return True
    return False

df["outlier_salary"] = df["salary"].apply(detect_outlier)

df

   age  salary  experience  purchased  outlier_salary
0   22   25000           1          0           False
1   25   30000           2          0           False
2   28   35000           3          1           False
3   32   50000           7          1           False
4   35   55000           8          1           False
5   40   70000          12          1           False
6   45   85000          15          1           False
7   30   45000           6          0           False
8   27   32000           4          0           False
9   38   65000          10          1           False

In [52]:
# Task 23 - remove outliers

df = df[df["outlier_salary"] == False]

df.drop(columns=["outlier_salary"], inplace=True)
df

   age  salary  experience  purchased
0   22   25000           1          0
1   25   30000           2          0
2   28   35000           3          1
3   32   50000           7          1
4   35   55000           8          1
5   40   70000          12          1
6   45   85000          15          1
7   30   45000           6          0
8   27   32000           4          0
9   38   65000          10          1

In [53]:
# Task 24 - Label encoding

df = pd.DataFrame({
    "color": ["Red", "Blue", "Green", "Red", "Blue"]
})

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["type"] = le.fit_transform(df["color"])

df

   color  type
0    Red     2
1   Blue     0
2  Green     1
3    Red     2
4   Blue     0

In [56]:
# Task 25 - one hot encoding

df = pd.DataFrame({
    "color": ["Red", "Blue", "Green", "Red", "Blue"]
})

encoded_df = pd.get_dummies(data=df,columns=["color"])
encoded_df

   color_Blue  color_Green  color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3       False        False       True
4        True        False      False

In [58]:
# Task 26 - Train/test split

from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    "age": [22, 25, 28, 32, 35, 40, 45, 30, 27, 38],
    "salary": [25000, 30000, 35000, 50000, 55000, 70000, 85000, 45000, 32000, 65000],
    "purchased": [0, 0, 1, 1, 1, 1, 1, 0, 0, 1]
})

X = df[["age", "salary"]]
y = df["purchased"]

X_train, X_test, y_train, y_test = train_test_split(
        X, y, random_state=42, test_size=0.20
    )

print(f"{(X_train.shape[0]/df.shape[0]) * 100}% Training")
print(f"{(X_test.shape[0]/df.shape[0]) * 100}% Testing")

80.0% Training
20.0% Testing

In [60]:
# Task 27 - Feature Scaling

df = pd.DataFrame({
    "age": [22, 25, 28, 32, 35, 40, 45, 30, 27, 38],
    "salary": [25000, 30000, 35000, 50000, 55000, 70000, 85000, 45000, 32000, 65000],
    "experience": [1, 2, 3, 7, 8, 12, 15, 6, 4, 10]
})

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["salary", "experience"]] = scaler.fit_transform(
    df[["salary", "experience"]]
)

df

   age    salary  experience
0   22 -1.299574   -1.346291
1   25 -1.031067   -1.114172
2   28 -0.762560   -0.882053
3   32  0.042961    0.046424
4   35  0.311468    0.278543
5   40  1.116989    1.207020
6   45  1.922510    1.903377
7   30 -0.225546   -0.185695
8   27 -0.923664   -0.649934
9   38  0.848482    0.742781

In [61]:
# Task 28 - ColumnTrasformer

df = pd.DataFrame({
    "age": [22, 25, 28, 32, 35, 40, 45, 30, 27, 38],
    "salary": [25000, 30000, 35000, 50000, 55000, 70000, 85000, 45000, 32000, 65000],
    "city": ["Chennai", "Mumbai", "Delhi", "Chennai", "Bangalore",
             "Mumbai", "Delhi", "Chennai", "Bangalore", "Mumbai"]
})

df["salary"] = scaler.fit_transform(df[["salary"]])

encoded_df = pd.get_dummies(df["city"], dtype=int)

df = pd.concat([df, encoded_df], axis=1)

df

   age    salary       city  Bangalore  Chennai  Delhi  Mumbai
0   22 -1.299574    Chennai          0        1      0       0
1   25 -1.031067     Mumbai          0        0      0       1
2   28 -0.762560      Delhi          0        0      1       0
3   32  0.042961    Chennai          0        1      0       0
4   35  0.311468  Bangalore          1        0      0       0
5   40  1.116989     Mumbai          0        0      0       1
6   45  1.922510      Delhi          0        0      1       0
7   30 -0.225546    Chennai          0        1      0       0
8   27 -0.923664  Bangalore          1        0      0       0
9   38  0.848482     Mumbai          0        0      0       1

In [63]:
# Task 29 - Linear Regression

from sklearn.linear_model import LinearRegression

df = pd.DataFrame({
    "hours_studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "marks": [35, 40, 45, 50, 55, 62, 68, 75, 82, 90]
})

X = df[["hours_studied"]]
y = df["marks"]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

lr = LinearRegression()

model = lr.fit(X_train, y_train)

model.predict(X_test)

array([81.30172414, 38.69827586])

In [ ]:
# Task 29 - Linear Regression

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

y_pred = model.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE :", round(mae, 2))
print("MSE :", round(mse, 2))
print("RMSE:", round(rmse, 2))
print("R²  :", round(r2, 2))

MAE : 1.0
MSE : 1.09
RMSE: 1.04
R²  : 1.0

In [66]:
# Task 30 - Multiple Linear Regression

df = pd.DataFrame({
    "experience": [1, 2, 3, 5, 7, 9, 11, 13, 15, 17],
    "age": [22, 24, 26, 29, 32, 35, 38, 41, 44, 47],
    "education": [12, 12, 14, 14, 16, 16, 16, 18, 18, 18],
    "salary": [25000, 28000, 32000, 40000, 48000, 55000, 65000, 75000, 85000, 95000]
})

X = df[["experience", "age", "education"]]
y = df[["salary"]]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()

model.fit(X_train, y_train)

model.predict(X_test)

array([[84069.76744186],
       [28267.44186047]])

In [68]:
# Task 31 - Logistic Regression

from sklearn.linear_model import LogisticRegression

df = pd.DataFrame({
    "age": [22, 25, 28, 32, 35, 40, 45, 30, 27, 38],
    "salary": [25000, 30000, 35000, 50000, 55000, 70000, 85000, 45000, 32000, 65000],
    "purchased": [0, 0, 0, 1, 1, 1, 1, 0, 0, 1]
})

X = df[["age", "salary"]]
y = df["purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression()

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [69]:
# Task 32 - Classification Metrics

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred))
print("Recall   :", recall_score(y_test, y_pred))
print("F1-score :", f1_score(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy : 1.0
Precision: 0.0
Recall   : 0.0
F1-score : 0.0
Confusion Matrix:
[[2]]

c:\Users\madhan.kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\madhan.kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 due to no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\madhan.kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\madhan.kumar\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:614: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(

In [70]:
from sklearn.tree import DecisionTreeClassifier

df = pd.DataFrame({
    "age": [22, 25, 28, 32, 35, 40, 45, 30, 27, 38],
    "salary": [25000, 30000, 35000, 50000, 55000, 70000, 85000, 45000, 32000, 65000],
    "purchased": [0, 0, 0, 1, 1, 1, 1, 0, 0, 1]
})

X = df[["age", "salary"]]
y = df["purchased"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

for depth in [1, 2, 3, 5, None]:
    model = DecisionTreeClassifier(max_depth=depth, random_state=42)
    model.fit(X_train, y_train)
    
    y_pred = model.predict(X_test)
    
    print("max_depth:", depth)
    print("Accuracy :", accuracy_score(y_test, y_pred))
    print()

max_depth: 1
Accuracy : 1.0

max_depth: 2
Accuracy : 1.0

max_depth: 3
Accuracy : 1.0

max_depth: 5
Accuracy : 1.0

max_depth: None
Accuracy : 1.0

In [ ]:
# Task 34 - Random Forest

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))

Random Forest Accuracy: 1.0

In [72]:
# Task 35 - KNN

from sklearn.neighbors import KNeighborsClassifier

for k in [3, 5, 7]:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)

    knn_pred = knn.predict(X_test)

    print(f"KNN (k={k}) Accuracy:", accuracy_score(y_test, knn_pred))

KNN (k=3) Accuracy: 1.0
KNN (k=5) Accuracy: 1.0
KNN (k=7) Accuracy: 0.0

In [73]:
# Task 36 - Handle Imbalanced data

y_test = np.array([0] * 950 + [1] * 50)

y_pred = np.array([0] * 1000)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, zero_division=0))
print("Recall   :", recall_score(y_test, y_pred, zero_division=0))
print("F1-score :", f1_score(y_test, y_pred, zero_division=0))

Accuracy : 0.95
Precision: 0.0
Recall   : 0.0
F1-score : 0.0

In [78]:
# Task 37 - cross-valdation

from sklearn.model_selection import cross_val_score

model = DecisionTreeClassifier()

scores = cross_val_score(
    model,
    X, y,
    cv=5,
    scoring="f1"
)

print("CV Scores:", scores)
print("Mean CV F1:", scores.mean().round(2))

CV Scores: [0. 1. 1. 1. 1.]
Mean CV F1: 0.8

In [80]:
# Task 38 - GridSearchCV
from sklearn.model_selection import GridSearchCV

params = {
    "max_depth": [1, 2, 3, 4, 5, 6, None]
}

grid = GridSearchCV(
    model,
    params,
    cv=5,
    scoring="f1"
)

grid.fit(X, y)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'max_depth': 2}
Best CV Score: 0.8

In [81]:
# Task 39 - Feature Importance


model = RandomForestClassifier(random_state=42)

model.fit(X, y)

importance = model.feature_importances_

for feature, score in zip(X.columns, importance):
    print(feature, score)

age 0.49
salary 0.51

In [82]:
# Task 40 - Complete ML mini-test

import pandas as pd

df = pd.DataFrame({
    "customer_age": [22, 25, 28, 35, 40, 45, 30, 27, 38, 50, 32, 29, 41, 36, 24],
    "income": [25000, 30000, 35000, 50000, 70000, 85000, 45000, 32000, 65000, 90000, 55000, 40000, 75000, 60000, 28000],
    "tenure": [1, 2, 3, 5, 7, 10, 4, 2, 6, 12, 5, 3, 8, 7, 1],
    "city": ["Chennai", "Mumbai", "Delhi", "Bangalore", "Chennai", "Mumbai", "Delhi", "Chennai", "Bangalore", "Mumbai", "Chennai", "Delhi", "Bangalore", "Mumbai", "Chennai"],
    "monthly_spend": [500, 700, 800, 1200, 1500, 1800, 900, 650, 1400, 2000, 1100, 750, 1600, 1300, 550],
    "churn": [0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0]
})

df.loc[3, "income"] = None
df.loc[7, "monthly_spend"] = None
df.loc[11, "city"] = None

df = pd.concat([df, df.iloc[[4]]], ignore_index=True)

df

    customer_age   income  tenure       city  monthly_spend  churn
0             22  25000.0       1    Chennai          500.0      0
1             25  30000.0       2     Mumbai          700.0      0
2             28  35000.0       3      Delhi          800.0      0
3             35      NaN       5  Bangalore         1200.0      1
4             40  70000.0       7    Chennai         1500.0      0
5             45  85000.0      10     Mumbai         1800.0      1
6             30  45000.0       4      Delhi          900.0      0
7             27  32000.0       2    Chennai            NaN      0
8             38  65000.0       6  Bangalore         1400.0      1
9             50  90000.0      12     Mumbai         2000.0      1
10            32  55000.0       5    Chennai         1100.0      0
11            29  40000.0       3        NaN          750.0      0
12            41  75000.0       8  Bangalore         1600.0      1
13            36  60000.0       7     Mumbai         1300.0      1
14            24  28000.0       1    Chennai          550.0      0
15            40  70000.0       7    Chennai         1500.0      0

In [83]:
print(df.head())
print(df.shape)
print(df.info())
print(df.describe())
print(df.columns)
print(df.dtypes)
print(df.isnull().sum())
print(df.duplicated().sum())

   customer_age   income  tenure       city  monthly_spend  churn
0            22  25000.0       1    Chennai          500.0      0
1            25  30000.0       2     Mumbai          700.0      0
2            28  35000.0       3      Delhi          800.0      0
3            35      NaN       5  Bangalore         1200.0      1
4            40  70000.0       7    Chennai         1500.0      0
(16, 6)
<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_age   16 non-null     int64
 1   income         15 non-null     float64
 2   tenure         16 non-null     int64
 3   city           15 non-null     str
 4   monthly_spend  15 non-null     float64
 5   churn          16 non-null     int64
dtypes: float64(2), int64(3), str(1)
memory usage: 1006.0 bytes
None
       customer_age        income     tenure  monthly_spend   churn
count     16.000000     15.000000  16.000000      15.000000  16.000
mean      33.875000  53666.666667   5.187500    1173.333333   0.375
std        8.057088  21681.679780   3.208712     463.244253   0.500
min       22.000000  25000.000000   1.000000     500.000000   0.000
25%       27.750000  33500.000000   2.750000     775.000000   0.000
50%       33.500000  55000.000000   5.000000    1200.000000   0.000
75%       40.000000  70000.000000   7.000000    1500.000000   1.000
max       50.000000  90000.000000  12.000000    2000.000000   1.000
Index(['customer_age', 'income', 'tenure', 'city', 'monthly_spend', 'churn'], dtype='str')
customer_age       int64
income           float64
tenure             int64
city                 str
monthly_spend    float64
churn              int64
dtype: object
customer_age     0
income           1
tenure           0
city             1
monthly_spend    1
churn            0
dtype: int64
1

In [84]:
print(df.isnull().sum())

customer_age     0
income           1
tenure           0
city             1
monthly_spend    1
churn            0
dtype: int64

In [85]:
df.drop_duplicates(inplace=True)

In [86]:
df[["income", "monthly_spend"]] = df[["income", "monthly_spend"]].fillna(
    df[["income", "monthly_spend"]].mean()
)

In [ ]:
df = pd.get_dummies(df, columns=["city"], dtype=int)

In [90]:
df

,customer_age,income,tenure,monthly_spend,churn,city_Bangalore,city_Chennai,city_Delhi,city_Mumbai
0,22,25000.0,1,500.0,0,0,1,0,0
1,25,30000.0,2,700.0,0,0,0,0,1
2,28,35000.0,3,800.0,0,0,0,1,0
3,35,52500.0,5,1200.0,1,1,0,0,0
4,40,70000.0,7,1500.0,0,0,1,0,0
5,45,85000.0,10,1800.0,1,0,0,0,1
6,30,45000.0,4,900.0,0,0,0,1,0
7,27,32000.0,2,1150.0,0,0,1,0,0
8,38,65000.0,6,1400.0,1,1,0,0,0
9,50,90000.0,12,2000.0,1,0,0,0,1
10,32,55000.0,5,1100.0,0,0,1,0,0
11,29,40000.0,3,750.0,0,0,0,0,0
12,41,75000.0,8,1600.0,1,1,0,0,0
13,36,60000.0,7,1300.0,1,0,0,0,1
14,24,28000.0,1,550.0,0,0,1,0,0

In [91]:
df.columns

Index(['customer_age', 'income', 'tenure', 'monthly_spend', 'churn',
       'city_Bangalore', 'city_Chennai', 'city_Delhi', 'city_Mumbai'],
      dtype='str')

In [93]:
X = df[['customer_age', 'income', 'tenure', 'monthly_spend',
       'city_Bangalore', 'city_Chennai', 'city_Delhi', 'city_Mumbai']]

y = df["churn"]

In [96]:
scaler = StandardScaler()

X[["customer_age", "income", "tenure", "monthly_spend"]] = scaler.fit_transform(
    X[["customer_age", "income", "tenure", "monthly_spend"]]
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [98]:
lr = LogisticRegression()

model = lr.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [99]:
print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, zero_division=0))
print("Recall   :", recall_score(y_test, y_pred, zero_division=0))
print("F1-score :", f1_score(y_test, y_pred, zero_division=0))

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1-score : 1.0

In [100]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[2, 0],
       [0, 1]])