In [16]:
import pandas as pd

bank_df = pd.read_csv("./Dataset/bank.csv")

In [17]:
bank_df

   Account  Deposit  Withdraw
0     1001     5000      1000
1     1002    10000      2000
2     1003     7000      9000

In [18]:
bank_df["Balance"] = bank_df["Deposit"] - bank_df["Withdraw"]

In [19]:
bank_df

   Account  Deposit  Withdraw  Balance
0     1001     5000      1000     4000
1     1002    10000      2000     8000
2     1003     7000      9000    -2000

In [20]:
def account_status(row):
    status = False
    if row["Balance"] >= 0:
        status = True

    row["Status"] = "OK" if status else "Overdrawn"
    return row

In [21]:
bank_df = bank_df.apply(account_status, axis = 1)

In [22]:
bank_df

   Account  Deposit  Withdraw  Balance     Status
0     1001     5000      1000     4000         OK
1     1002    10000      2000     8000         OK
2     1003     7000      9000    -2000  Overdrawn

In [23]:
final_bank_df = bank_df[["Account", "Balance", "Status"]]

In [ ]:
final_bank_