In [14]:
import pandas as pd

inventory_df = pd.read_csv("./Dataset/inventory.csv")

In [15]:
inventory_df

    Product  Stock
0    Laptop   10.0
1     Mouse   -5.0
2  Keyboard   20.0
3   Monitor    NaN

In [16]:
inventory_df.loc[inventory_df["Stock"] < 0, "Stock"] = 0

In [17]:
inventory_df

    Product  Stock
0    Laptop   10.0
1     Mouse    0.0
2  Keyboard   20.0
3   Monitor    NaN

In [18]:
inventory_df.loc[inventory_df["Stock"].isna(), "Stock"] = 0

In [19]:
inventory_df

    Product  Stock
0    Laptop   10.0
1     Mouse    0.0
2  Keyboard   20.0
3   Monitor    0.0

In [20]:
def fill_status(stock):
    if stock == 0:
        return "Out of Stock"
    elif stock >= 1 and stock < 11:
        return "Low"
    else:
        return "Available"

In [23]:
inventory_df["Status"] = inventory_df["Stock"].apply(fill_status)

In [24]:
inventory_df

    Product  Stock        Status
0    Laptop   10.0           Low
1     Mouse    0.0  Out of Stock
2  Keyboard   20.0     Available
3   Monitor    0.0  Out of Stock