In [1]:
import pandas as pd

student_df = pd.read_csv("./Dataset/student.csv")

In [2]:
student_df

  Student  Math  Science
0    John    80     90.0
1    Emma    70      NaN
2     Raj   100     95.0

In [3]:
student_df["Science"] = student_df["Science"].fillna(student_df["Science"].mean())

In [4]:
student_df

  Student  Math  Science
0    John    80     90.0
1    Emma    70     92.5
2     Raj   100     95.0

In [5]:
student_df["Total"] = student_df["Math"] + student_df["Science"]

In [6]:
student_df

  Student  Math  Science  Total
0    John    80     90.0  170.0
1    Emma    70     92.5  162.5
2     Raj   100     95.0  195.0

In [8]:
student_df["Percentage"] = student_df["Total"] / 2

In [9]:
student_df

  Student  Math  Science  Total  Percentage
0    John    80     90.0  170.0       85.00
1    Emma    70     92.5  162.5       81.25
2     Raj   100     95.0  195.0       97.50

In [11]:
def fill_grade(percent):
    if 90 <= percent <= 100:
        return "A"
    elif 75 <= percent <= 89:
        return "B"
    elif 50 <= percent <= 74:
        return "C"
    elif percent < 50:
        return "D"
    else:
        return "Unknown"

In [12]:
student_df["Grade"] = student_df["Percentage"].apply(fill_grade)

In [14]:
student_df

  Student  Math  Science  Total  Percentage Grade
0    John    80     90.0  170.0       85.00     B
1    Emma    70     92.5  162.5       81.25     B
2     Raj   100     95.0  195.0       97.50     A

In [15]:
final_student_df = student_df[["Student", "Grade"]]

In [16]:
final_student_df

  Student Grade
0    John     B
1    Emma     B
2     Raj     A

In [17]:
final_student_df.to_csv("./final_student.csv")