In [1]:
import pandas as pd

patient_df = pd.read_csv("./Dataset/patient.csv")

In [2]:
patient_df

  Patient    Age Gender
0    John   35.0      M
1    Emma    NaN      F
2     Raj  150.0      M
3   Chris   29.0    NaN

In [8]:
avg_age = patient_df.loc[
    (patient_df["Age"] < 120) & (patient_df["Age"].notna()),
    "Age"
].mean()

In [13]:
patient_df.loc[
    (patient_df["Age"] > 120) & (patient_df["Age"].isna()),
    "Age"
] = avg_age

In [14]:
patient_df

  Patient    Age Gender
0    John   35.0      M
1    Emma    NaN      F
2     Raj  150.0      M
3   Chris   29.0    NaN

In [18]:
patient_df = patient_df.fillna("Unknown")

In [19]:
patient_df

  Patient      Age   Gender
0    John     35.0        M
1    Emma  Unknown        F
2     Raj    150.0        M
3   Chris     29.0  Unknown