In [1]:
import pandas as pd

employee_df = pd.read_csv("./Dataset/employee.csv")

In [2]:
employee_df

   EmpID   Name Department   Salary
0      1    Raj         IT  50000.0
1      2   John         HR  45000.0
2      3   Emma         IT      NaN
3      4  Chris      Sales  35000.0

In [4]:
department_avg = employee_df.groupby("Department")["Salary"].mean()

In [6]:
department_avg

Department
HR       45000.0
IT       50000.0
Sales    35000.0
Name: Salary, dtype: float64

In [9]:
def fill_salary(row):
    if pd.isna(row["Salary"]):
        dept = row["Department"]
        match dept:
            case "HR":
                row["Salary"] = department_avg["HR"]
            case "IT":
                row["Salary"] = department_avg["IT"]
            case "Sales":
                row["Salary"] = department_avg["Sales"]
    return row

In [10]:
employee_df = employee_df.apply(fill_salary, axis = 1)

In [11]:
employee_df

   EmpID   Name Department   Salary
0      1    Raj         IT  50000.0
1      2   John         HR  45000.0
2      3   Emma         IT  50000.0
3      4  Chris      Sales  35000.0

In [12]:
employee_df["Bonus"] = employee_df["Salary"] * 1.10

In [13]:
employee_df

   EmpID   Name Department   Salary    Bonus
0      1    Raj         IT  50000.0  55000.0
1      2   John         HR  45000.0  49500.0
2      3   Emma         IT  50000.0  55000.0
3      4  Chris      Sales  35000.0  38500.0

In [15]:
final_employee_df = employee_df[["Name", "Salary", "Bonus"]]

In [16]:
final_employee_df

    Name   Salary    Bonus
0    Raj  50000.0  55000.0
1   John  45000.0  49500.0
2   Emma  50000.0  55000.0
3  Chris  35000.0  38500.0

In [ ]:
final_employee_df.