In [2]:
import json
import pandas as pd

csv_data = pd.read_csv("./Dataset/csv_data.csv")
json_data = pd.read_json("./Dataset/api.json")

In [3]:
csv_data

  ProductID Product  Price
0      P101  Laptop  50000
1      P102   Mouse    800

In [4]:
json_data

  ProductID  Stock
0      P101     20
1      P102     15

In [5]:
df = json_data.merge(csv_data, on="ProductID")

In [6]:
df

  ProductID  Stock Product  Price
0      P101     20  Laptop  50000
1      P102     15   Mouse    800

In [7]:
df.to_csv("./final_df.csv")